name: 'Test Action'

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
      - 'releases/**'
  workflow_dispatch:
##TODO - ADD NIGHTLY CRON JOB TEST FOR ALL VERSIONS

permissions:
  contents: read

jobs:
  test-action:
    name: 'Test Build Composer Satis Repository'
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repository
        name: 'Checkout Repository'
        uses: actions/checkout@v4

      - id: create-satis-json
        name: 'Create Configuration File'
        run: |
          cd ${{ github.workspace }}
          cat << EOF > satis.json
          {
            "name": "mattgrul/test-packages",
            "homepage": "http://packages.test.org",
            "repositories": [
              {
                "type": "vcs",
                "url": "https://github.com/composer/satis"
              }
            ],
            "require-all": true
          }
          EOF

      - id: generate-satis-repo
        name: 'Test Run Generate Satis Repository Action'
        uses: ./
        env:
          SATIS_PATH: ${{ github.workspace }}/satis

      - id: test-pass
        if: ${{ success() }}
        name: 'Test Pass'
        run: echo "Test PASS"
        shell: bash

      - id: check_artifact
        if: ${{ failure() }}
        name: 'Test Fail'
        run: echo "Test FAIL"
        shell: bash
